"""add wc2026 fixtures table

Revision ID: 202f3945b5b9
Revises: 
Create Date: 2026-06-15 20:23:08.955568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202f3945b5b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wc2026_fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('group_name', sa.String(length=5), nullable=True),
    sa.Column('round_name', sa.String(length=50), nullable=True),
    sa.Column('team_a_name', sa.String(length=100), nullable=True),
    sa.Column('team_b_name', sa.String(length=100), nullable=True),
    sa.Column('team_a_id', sa.Integer(), nullable=True),
    sa.Column('team_b_id', sa.Integer(), nullable=True),
    sa.Column('feeds_from_a', sa.Integer(), nullable=True),
    sa.Column('feeds_from_b', sa.Integer(), nullable=True),
    sa.Column('pred_team_a_prob', sa.Float(), nullable=True),
    sa.Column('pred_draw_prob', sa.Float(), nullable=True),
    sa.Column('pred_team_b_prob', sa.Float(), nullable=True),
    sa.Column('predicted_winner', sa.String(length=100), nullable=True),
    sa.Column('actual_score_a', sa.Integer(), nullable=True),
    sa.Column('actual_score_b', sa.Integer(), nullable=True),
    sa.Column('actual_winner', sa.String(length=100), nullable=True),
    sa.Column('is_played', sa.Boolean(), nullable=True),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wc2026_fixtures')
    # ### end Alembic commands ###
