"""initial schema

Revision ID: 43954d8ec10f
Revises: 
Create Date: 2026-05-30 14:24:56.181205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43954d8ec10f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('predictions_match_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('predictions_match_id_key'), ['match_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
