"""allow nullable match_id

Revision ID: f15ac2de741a
Revises: 43954d8ec10f
Create Date: 2026-05-30 14:36:29.206410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15ac2de741a'
down_revision = '43954d8ec10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
